server:
  port: 8081

mybatis:
  mapper-locations:
    - classpath*:mapper/*.xml

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    name: DruidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://106.15.200.82:3306/pytap_blog?useSSL=FALSE&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: guowei00a
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: user
        login-password: qwer1234
  aop:
    auto: true

logging:
  level:
    com.pytap.blog.dao: debug

jwt:
  tokenHeader: Authorization
  secret: spring-security
  expiration: 604800
  tokenHead: Bearer